### ISSUE TITLE
Error: ENOENT: no such file or directory, open .../node_modules/ignore/ignore.js

### ISSUE THREAD

**Issue by chrischambers** [mantoni/eslint_d.js#97] opened 2018-10-08 13:49 UTC
Looks like this has been broken since https://github.com/kaelzhang/node-ignore/commit/cbad90

**Comment by mantoni** [comment] 2018-10-08 15:34
Can you explain how to produce this error?

**Comment by mantoni** [comment] 2018-10-11 16:37
Ok, so no explanation and no further reports. Closing.

**Closed by mantoni** 2018-10-11 16:37 UTC

**Comment by chrischambers** [comment] 2018-10-16 13:49
Apologies, I meant to get back to you when I could replicate this, but it seemed to be something particular to my local dev environment. Resolved, thanks.

**Comment by mantoni** [comment] 2018-10-16 15:59
No worries. Thanks for coming back👌

**Comment by zhenyulin** [comment] 2018-11-15 17:07
getting a similar issue when running eslint_d today, when running the bin I got the following error:

```
Error: ENOENT: no such file or directory, open '..../node_modules/pkg-dir/node_modules/find-up/index.js'
```

**Comment by mantoni** [comment] 2018-11-15 17:09
@zhenyulin Can you verify this works with normal `eslint`? Can I also ask you to provide instructions on how to reproduce?

**Comment by zhenyulin** [comment] 2018-11-15 17:15
@mantoni yes, `eslint` works for me, and it runs into this issue after I cp a repo locally to make a new one, and it still works in the original repo, so I suspect it might be some cache issue

**Comment by mantoni** [comment] 2018-11-15 17:16
@zhenyulin Most probably. Can you check if `eslint_d restart` makes the issue disappear?

**Comment by zhenyulin** [comment] 2018-11-15 17:18
@mantoni yes, it fixes the issue

though I'm getting the following from the command
```
Already running
Could not connect
```
which is a slightly confusing

was curious about how the cache was generated in eslint_d, is it bound to a hidden dir?
