### ISSUE TITLE
`Failed to load parser` when changing branches

### ISSUE THREAD

**Issue by aaronjensen** [mantoni/eslint_d.js#113] opened 2019-07-19 00:12 UTC
Our team often sees this when running eslint_d:

```
Error: Failed to load parser '/Users/username/Projects/proj/node_modules/@typescript-eslint/parser/dist/parser.js' declared in '.eslintrc.js » /Users/username/Projects/proj/node_modules/@substantial/our-util-scripts/config/eslintrc.js#overrides[1]': ENOENT: no such file or directory, open '/Users/username/Projects/proj/node_modules/@typescript-eslint/parser/node_modules/@typescript-eslint/experimental-utils/dist/index.js'
```

An `eslint_d stop` fixes it, but it costs us time and often confuses people who are newer to the project. Any idea on why the change detection isn't working in cases like this?

**Comment by mantoni** [comment] 2019-07-23 15:02
Hmmm, maybe it's because the require cache is only cleared for files within the `cwd` here:

https://github.com/mantoni/eslint_d.js/blob/8abbf0d56ef4bbfc0ef884d81b53c778ed71a887/lib/linter.js#L55-L61

If you can reproduce, you could try to modify the code to always clear the entire require cache and see if that fixes. it.

**Comment by mantoni** [comment] 2019-07-23 15:03
And sorry for the late response. I'm drowning in lodash security notifications.

**Comment by aaronjensen** [comment] 2019-07-25 05:58
It generally happens when run from `lint-staged`, which, I'm pretty sure only runs from the project root, so I'm not sure that's it. It's helpful to know where that code is though, I'll think about it.

**Comment by sangdth** [comment] 2022-02-01 14:45
I'm using eslint_d for my neovim null-ls custom linter, and every now and then, for example, when I remove/install some package, this issue appears!

I tried the suggestion from @aaronjensen, stop it and it works again. So I guess it relates to this.

**Comment by mantoni** [comment] 2022-02-02 08:04
Removing or installing packages should be tracked by checking the last modified timestamp on the `package.json` file. If that doesn't work, it's a bug. It'd be great if someone could come up with a step by step guide how to reproduce the issue.

@aaronjensen If you have a way to reproduce with `lint-staged` that I can follow, that could help too. I'm never running into this issue myself.

**Comment by sangdth** [comment] 2022-02-04 09:24
I don't see issue any more. So I think if nobody can reproduce it, let's close the issue for now. I will try to find a way to reproduce when it's less busy :D

**Comment by GabrielDuarteM** [comment] 2022-05-20 00:29
I got this error, and no matter what I did, the error would only happen on that specific folder. If I just copy the whole folder under a different name, it would run fine...

It was basically a brand new `yarn create next-app --typescript`, and started happening after I did `yarn add tailwindcss` (I remember I deleted the whole node_modules folder and reinstalled, not sure if that could also be related)

It solved after I killed the eslint_d process, so seems to be some sort of internal error? If I get to reproduce it again, I'll post it here.

And just for the sake of googling, here's the error that happen with me:

```
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json » eslint-config-next/core-web-vitals » /Users/gabe/projects/site/node_modules/eslint-config-next/index.js#overrides[0]': ENOENT: no such file or directory, open '/Users/gabe/projects/site/node_modules/fast-glob/node_modules/glob-parent/index.js'
```

**Comment by mantoni** [comment] 2022-05-26 17:53
We discovered a flaw with hashing the common package manager files to invalidate the `eslint_d` internal caches. I'm relatively sure to have addressed this issue with the new implementation in `v12.2.0`.

If anyone runs into this issue again, please feel free to open a new ticket. ❤️

**Closed by mantoni** 2022-05-26 17:53 UTC
